import type { Lang } from "@/lib/i18n/common";

export const CLIENT_CASES: Record<
  Lang,
  { logo: string; slug: string; bg: string; company: string; sector: string; metric: string; text: string; bullets: string[]; outcome: string; photo: string; flip?: boolean }[]
> = {
  nl: [
    {
      logo: "HP",
      slug: "hotelplanner",
      bg: "#3A0CA3",
      company: "HotelPlanner",
      sector: "Internationale travel-tech scale-up",
      metric: "6 plaatsingen Business Development",
      text: "Werkstudenten die meedraaien in het commerciële team, 24-40 uur per week, langer dan een jaar.",
      bullets: [
        "Leads identificeren en kwalificeren via deskresearch",
        "Cold outreach via telefoon en e-mail",
        "CRM-beheer en opvolging van de pipeline",
      ],
      outcome: "Inmiddels zes plaatsingen. De eerste werkstudent groeide door naar een vaste rol.",
      photo: "/photography/case-traveltech.jpg",
    },
    {
      logo: "EZ",
      slug: "enerzien",
      bg: "#6A44C4",
      company: "Enerzien",
      sector: "Advies & engineering voor smart energy systems",
      metric: "Werkstudent Marketing & Communicatie",
      text: "16-24 uur per week, 6+ maanden, verantwoordelijk voor de marketing- en contentstrategie.",
      bullets: [
        "Marketing- en contentstrategie ontwikkelen en uitvoeren",
        "Copy schrijven voor LinkedIn, website en externe communicatie",
        "Leadgeneratie ondersteunen, afgestemd op het salesproces",
      ],
      outcome: "Koos bewust voor een werkstudent in plaats van een klassieke stagiair. Nog steeds aan boord.",
      photo: "/photography/case-terra.jpg",
    },
    {
      logo: "JZ",
      slug: "joulz",
      bg: "#4476F2",
      company: "Joulz",
      sector: "Energie & infrastructuur",
      metric: "3 werkstudenten Finance",
      text: "16-24 uur per week, 12+ maanden, in de financiële operatie van het bedrijf.",
      bullets: [
        "Facturatie en debiteurenbeheer verwerken en opvolgen (O2C)",
        "Inkoopfacturen verwerken en bankreconciliatie ondersteunen (P2P)",
        "Facturen matchen aan orders en afwijkingen signaleren",
      ],
      outcome: "Drie betrokken werkstudenten die blijven. De kwaliteit en continuïteit die eerder ontbrak.",
      photo: "/photography/case-finance.jpg",
    },
    {
      logo: "SC",
      slug: "structural-collective",
      bg: "#3A0CA3",
      company: "Structural Collective",
      sector: "Onderzoek & advies, duurzaamheid en impact",
      metric: "Werkstudent Communicatie",
      text: "16 uur per week, 6 maanden, verantwoordelijk voor communicatie richting buiten.",
      bullets: [
        "Onderzoeksresultaten vertalen naar toegankelijke content en copy",
        "Persberichten, LinkedIn-posts en websitecontent schrijven",
        "Rapportages en publicaties ondersteunen",
      ],
      outcome: "Senior consultants structureel ontlast om zich op inhoudelijk werk te richten.",
      photo: "/photography/companies-band.jpg",
      flip: true,
    },
    {
      logo: "LS",
      slug: "the-longevity-store",
      bg: "#6A44C4",
      company: "The Longevity Store",
      sector: "E-commerce, longevity en supplementen",
      metric: "2 plaatsingen Founder's Associate",
      text: "40 uur per week, 6 maanden, direct samenwerkend met de founders.",
      bullets: [
        "AI-tools implementeren in interne processen en workflows",
        "Terugkerende taken automatiseren, processen optimaliseren",
        "Meedenken met de founders over strategische vraagstukken",
      ],
      outcome: "Twee plaatsingen, waarvan er één binnen 3 maanden een vast aanbod kreeg.",
      photo: "/photography/case-longevity-store.jpg",
    },
  ],
  en: [
    {
      logo: "HP",
      slug: "hotelplanner",
      bg: "#3A0CA3",
      company: "HotelPlanner",
      sector: "International travel-tech scale-up",
      metric: "6 placements, Business Development",
      text: "Working students embedded in the commercial team, 24-40 hours a week, over a year.",
      bullets: [
        "Identifying and qualifying leads through desk research",
        "Cold outreach by phone and email",
        "CRM management and pipeline follow-up",
      ],
      outcome: "Six placements to date. The first working student has since grown into a full-time role.",
      photo: "/photography/case-traveltech.jpg",
    },
    {
      logo: "EZ",
      slug: "enerzien",
      bg: "#6A44C4",
      company: "Enerzien",
      sector: "Advisory & engineering for smart energy systems",
      metric: "Working student, Marketing & Communication",
      text: "16-24 hours a week, 6+ months, owning the marketing and content strategy.",
      bullets: [
        "Developing and executing marketing and content strategy",
        "Writing copy for LinkedIn, website and external communications",
        "Supporting lead generation, aligned with the sales process",
      ],
      outcome: "Chose a working student over a classic intern. Still on board.",
      photo: "/photography/case-terra.jpg",
    },
    {
      logo: "JZ",
      slug: "joulz",
      bg: "#4476F2",
      company: "Joulz",
      sector: "Energy & infrastructure",
      metric: "3 working students, Finance",
      text: "16-24 hours a week, 12+ months, inside the company's financial operations.",
      bullets: [
        "Processing and following up on invoicing and receivables (O2C)",
        "Processing purchase invoices and supporting bank reconciliation (P2P)",
        "Matching invoices to orders and flagging discrepancies",
      ],
      outcome: "Three engaged working students who stay. The quality and continuity that had been missing.",
      photo: "/photography/case-finance.jpg",
    },
    {
      logo: "SC",
      slug: "structural-collective",
      bg: "#3A0CA3",
      company: "Structural Collective",
      sector: "Research & advisory, sustainability and impact",
      metric: "Working student, Communication",
      text: "16 hours a week, 6 months, owning external communication.",
      bullets: [
        "Translating research findings into accessible content and copy",
        "Writing press releases, LinkedIn posts and website content",
        "Supporting reports and publications",
      ],
      outcome: "Senior consultants structurally freed up to focus on substantive work.",
      photo: "/photography/companies-band.jpg",
      flip: true,
    },
    {
      logo: "LS",
      slug: "the-longevity-store",
      bg: "#6A44C4",
      company: "The Longevity Store",
      sector: "E-commerce, longevity and supplements",
      metric: "2 placements, Founder's Associate",
      text: "40 hours a week, 6 months, working directly with the founders.",
      bullets: [
        "Implementing AI tools in internal processes and workflows",
        "Automating repetitive tasks, optimising operational processes",
        "Working directly with the founders on strategic questions",
      ],
      outcome: "Two placements, one of which received a full-time offer within 3 months.",
      photo: "/photography/case-longevity-store.jpg",
    },
  ],
};
